name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  hello-world:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
      - name: Echo  
        uses: .github/actions/echo
        env:
          SHH_SECRET: ${{ secrets.SHH_SECRET }}
          NORMAL_VARIABLE: ${{ vars.NORMAL_VARIABLE }}